on:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'fix-code-coverage'

name: Upload Code Coverage

jobs:
  test:
    name: Integration test
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:storybook:test
          wait-on: 'http://localhost:57021'
          browser: chrome
      - name: Generate code coverage report
        run: yarn run nyc report --reporter=clover --reporter=text --report-dir=./coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          fail_ci_if_error: false
